version: '3'

services:
  node01:
    build: ./node01
    container_name: node01
    tty: true
    command: /bin/bash -c "/bin/bash /tmp/init.sh && /bin/bash"
    ports:
      - '11001:3306'

  node02:
    build: ./node02
    container_name: node02
    tty: true
    command: /bin/bash -c "/bin/bash /tmp/init.sh && /bin/bash"
    depends_on:
      - node01
    ports:
      - '11002:3306'

  node03:
    build: ./node03
    container_name: node03
    tty: true
    command: /bin/bash -c "/bin/bash /tmp/init.sh && /bin/bash"
    depends_on:
      - node01
    ports:
      - '11003:3306'

  node04:
    build: ./node04
    container_name: node04
    tty: true
    command: /bin/bash -c "/bin/bash /tmp/init.sh && /bin/bash"
    depends_on:
      - node01
    ports:
      - '11004:3306'

  node05:
    build: ./node05
    container_name: node05
    tty: true
    command: /bin/bash -c "/bin/bash /tmp/init.sh && /bin/bash"
    ports:
      - '11005:3306'

