version: '3'

services:
  node01:
    build: ./node01
    container_name: node01
    tty: true
    command: /bin/bash -c "/bin/bash /tmp/init.sh && /bin/bash"
    ports:
      - '11101:3306'

  node02:
    build: ./node02
    container_name: node02
    tty: true
    command: /bin/bash -c "/usr/bin/supervisord -c /etc/supervisord.conf && /bin/bash"
    depends_on:
      - node01
    ports:
      - '11102:3306'

  node03:
    build: ./node03
    container_name: node03
    tty: true
    command: /bin/bash -c "/usr/bin/supervisord -c /etc/supervisord.conf && /bin/bash"
    depends_on:
      - node01
    ports:
      - '11103:3306'

  node04:
    build: ./node04
    container_name: node04
    tty: true
    command: /bin/bash -c "/usr/bin/supervisord -c /etc/supervisord.conf && /bin/bash"
    depends_on:
      - node01
    ports:
      - '11104:3306'

  node05:
    build: ./node05
    container_name: node05
    tty: true
    command: /bin/bash -c "/usr/bin/supervisord -c /etc/supervisord.conf && /bin/bash"
    ports:
      - '11105:3306'

